name: Gradle Build and SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        working-directory: volts-server
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: volts-server
        run: ./gradlew build

      - name: SonarQube Analysis
        working-directory: volts-server
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: List build directory
        working-directory: volts-server
        run: ls -la build/libs

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          working-directory: volts-server
          name: my-app-build
          path: build/libs/*.jar

      - name: Commit JAR file to repository
        working-directory: volts-server
        run: |
          git config user.name "IvoRum"
          git config user.email "ivaylo.rumenov@outlook.com"
          git add build/libs/*.jar
          git commit -m "Add build artifacts"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
